### ISSUE TITLE
[question] Why node16 is required

### ISSUE THREAD

**Issue by micalevisk** [SuperchupuDev/neon-env#1]
Can you clarify on why we need to use node16+ ? Because I just tested it with node v14.17.3 and it worked as expected so far:

![image](https://user-images.githubusercontent.com/13461315/198904029-6bbd8060-819a-4280-b92a-adf11a9bb110.png)

is it because of the usage of `node:` protocol? because it is available in [nodejs v14.13.1 for ESM modules](https://2ality.com/2021/12/node-protocol-imports.html#support-for-node%3A-imports)

**Comment by SuperchupuDev** [comment]
I'm aware that it got backported to v14, but it's gonna reach EOL soon and I was too busy to quickly search how to allow v14 and >v16 but not v15 (which didn't get the backport) in the `engine` package field. Feel free to make a PR, otherwise i'll make it at some point

**Comment by SuperchupuDev** [comment]
Since this lib generates both CJS and ESM code I guess the minimum should be set to v14.18.0 and above (without taking v15 into account)
![image](https://user-images.githubusercontent.com/53496941/198904996-162dc333-1cb8-4f3a-a37e-583c6ad4b776.png)

**Comment by micalevisk** [comment]
got it

I'll open a PR then, thanks
